main = ".open-next/worker.js"
name = "orion-prototype"
compatibility_date = "2025-04-17"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[vars]
NEXT_PUBLIC_APP_PASSWORD = "orionvibes"