main = ".open-next/worker.js"
name = "orion-prototype"
compatibility_date = "2024-03-25"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[services]
binding = "WORKER_SELF_REFERENCE"
service = "orion-prototype" 